name: 'Create Issue for Pull Request'
description: 'Creates a new issue to track a merged pull request'
inputs:
  github-token:
    description: 'GitHub token with read and write access on the project.'
    required: true
runs:
  using: 'node12'
  main: 'index.js'