name: Create Pull Request Issue
on:
  pull_request:
    types: [closed]
jobs:
  createIssue:
    name: Create Issue
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: Create Issue
        uses: ./.github/actions/create-pull-request-issue
        with:
          github-token: ${{ secrets.GH_PAT }}
